# ===================================================================
# Fichero de configuración Entorno Producción
# ===================================================================

# # ===============================
# = HTTP Server
# # ===============================
server:
  port: 9080

# # ===============================
# = SPRING BOOT GENERAL
# # ===============================
spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/springboot_course_db
    username: root
    password: secret
    jpa:
      show-sql: false